app.js, controller/users.js, middlewares/authmiddleware.js, package-lock.json, package.json, passport/index.js, passport/kakaoStrategy.js, passport/localStrategy.js, routes/middlewares.js, routes/users.js, schemas/user.js, 창민 진행상황.md
=> refreshtoken 수정, 카카오 소셜로그인 구현

controller/mypage.js
=> [fix] 프로필 조회 find->findOne 변경

controller/placeComments.js, controller/recruitComments.js, controller/reviewComments.js, routes/placeComments.js, routes/reviewComments.js
=> 댓글(모집,장소추천,물품리뷰) 추가

app.js
=> [fix] socket 수정

app.js
=> [fix] socket io부분 to 삭제

app.js
=> [fix] socket 수정2

app.js
=> [fix] socket async 수정

app.js
=> [fix] socket to 제거

app.js
=> [fix] io -> socket 변경

app.js
=> [fix] socket->io로 변경

app.js, controller/chatRooms.js, controller/recruitPosts.js, package-lock.json, package.json, schemas/chatRoom.js, swagger-output.json, swagger.js
=> [update] 소켓 테스트&swagger 초안

app.js
=> [fix] socket 수정(io.emit)

app.js, controller/bookmarks.js, controller/recruitPosts.js, routes/bookmarks.js, routes/recruitPosts.js, schemas/bookmark.js, schemas/chatMessage.js, schemas/recruitPost.js
=> [test] 모집 게시글 수정

app.js, controller/bookmarks.js, controller/recruitPosts.js, routes/bookmarks.js, routes/recruitPosts.js, schemas/bookmark.js
=> [fix] 모집 게시물 수정

controller/chatMessages.js, controller/chatRooms.js, controller/mypages.js, controller/placeComments.js, controller/placePosts.js, controller/recruitComments.js, controller/reviewComments.js, controller/reviewPosts.js, schemas/chatMessage.js, schemas/chatRoom.js, socket.js
=> [fix] 프로필 이미지 url 수정

controller/chatMessages.js, controller/chatRooms.js, routes/chatRooms.js, schemas/chatMessage.js, schemas/chatRoom.js, socket.js
=> [test] 테스트

app.js, controller/chatRooms.js, package-lock.json, package.json
=> [add] 중간발표전 작업물 최종

controller/placePosts.js, controller/recruitPosts.js, controller/reviewPosts.js, schemas/placePost.js, schemas/reviewPost.js
=> [fix] recruitPosts date 날짜 자름

controller/mypages.js, controller/placePosts.js, controller/recruitPosts.js, controller/reviewPosts.js, middlewares/authmiddleware.js, routes/placePosts.js, routes/reviewPosts.js, schemas/placeBookmark.js, schemas/recruitBookmark.js, schemas/reviewBookmark.js
=> 북마크한 순서대로 마이페이지에 보이도록

controller/recruitPosts.js, controller/searchs.js, controller/users.js, middlewares/authmiddleware.js
=> Kakao login

controller/chatRooms.js, controller/mypages.js, controller/reviewPosts.js, middlewares/mainMulter.js
=> [fix] 이미지 수정 코드 변경

controller/recruitPosts.js, routes/placePosts.js
=> [fix] 이미지 3개로 수정

controller/reviewPosts.js
=> [fix] 이미지 코드 수정

app.js, controller/mypages.js, controller/reviewPosts.js, swagger.js
=> [fix] 이미지 부분 수정

controller/placePosts.js, middlewares/mainMulter.js, schemas/placePost.js
=> [fix] 이미지 limits 변경

controller/placeComments.js, controller/recruitComments.js, controller/reviewComments.js, schemas/placeComment.js
=> 댓글 시간 등록 수정 2

controller/recruitPosts.js
=> 북마크 수정 기능 수정

app.js, controller/chatRooms.js, data/signup.json, schemas/chatRoom.js, server.js
=> [fix] 서버 실행 파일 분리

app.js, package-lock.json
=> [fix] passportConfig 삭제

app.js, controller/chatRooms.js, server.js, socket.js
=> [fix] 소켓 파일 정리

.gitignore, app.js, controller/mains.js, controller/mypages.js, controller/placeComments.js, controller/placePosts.js, controller/recruitComments.js, controller/recruitPosts.js, controller/reviewComments.js, controller/reviewPosts.js, controller/searchs.js, controller/users.js, logger.js, middlewares/authmiddleware.js, package-lock.json, package.json, server.js
=> winston 적용

app.js, controller/users.js
=> [fix] 이메일 try~catch 주석 처리

controller/chatRooms.js, controller/placePosts.js
=> [update] 장소추천 게시글 빈칸 예외처리

controller/placePosts.js, controller/reviewPosts.js, middlewares/mainMulter.js, schemas/placePost.js
=> [fix] 병합 충돌 해결
